@startuml
'https://plantuml.com/class-diagram
!theme blueprint

abstract class AbstractMenu {
  - inventory : Inventory
  - previousMenu : Menu
  + setItem(slot : int, item : ItemStack)
}

interface View {
  + getSlots() : List<Integer>
  + update()
}

class ElementView {
  + getElement() : Element
}

@enduml